feat(@multi-frontend/calendar): visualisation alternative pour le widget
univlorraine/esup-multi pull request #38
Opened 2024-05-30 16:33 UTC by gdeudon

Bonjour,

Voilà la contribution de l'UPHF pour le calendrier.

Nous avons ajouté une vue alternative du widget de calendrier. Celle-ci affiche les rendez-vous sous la forme d'un défilement horizontal.

Nous avons eu besoin du pipe _LocalHourPipe_ du module _schedule_, nous l'avons donc déplacé dans le module _shared_, puis fait le changement d'import dans le module _schedule_. C'est pourquoi les modules _shared_ et _schedule_ s'en retrouvent modifiés.

Bonne fin de journée

2024-06-21 07:15 UTC, ActxLeToucan requested changes
Bonjour,

Merci pour cette contribution.
Comme pour la pr #36, il y a un souci au niveau des couleurs :
![image](https://github.com/univlorraine/esup-multi/assets/56509120/6d0c9549-f4f4-4283-94ea-385b92e4689e)

Quelques petites améliorations avant de merge :
* ajouter la nouvelle config dans `dev/user-frontend-ionic/src/environments/environment.ts.dist`
* ajouter une marge en bas du widget en mode slider
* corriger la couleur de l'icône `business-outline` en passant, en ajoutant la classe css `fontColor()`

Bonne journée

2024-10-08 13:59 UTC, gdeudon commented
Bonjour,

C'est corrigé !

bonne journée ✌️

2024-10-22 14:20 UTC, ActxLeToucan approved these changes

2024-10-24 08:16 UTC, benjhoo approved these changes

2024-10-24 08:17 UTC, merged